# Base image
FROM python:3.10

# Set the working directory
WORKDIR /app

# Set PYTHONPATH to treat /app as a package root
ENV PYTHONPATH=/app

# Install dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Copy the rest of the app code
COPY app /app

# Start the app
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
